# Generated by Django 4.2.27 on 2026-02-27 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0004_remove_lobby_level_lobby_elo_max_lobby_elo_min_and_more'),
        ('memberships', '0003_membershiptype_discount_on_court_and_more'),
        ('finance', '0004_transaction_payment_method_and_more'),
        ('bookings', '0006_booking_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('provider', models.CharField(choices=[('stub', 'Stub (разработка)'), ('kaspi', 'Kaspi QR'), ('card', 'Банковская карта'), ('cash', 'Наличные (касса)')], default='stub', max_length=20, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('SUCCESS', 'Оплачено'), ('FAILED', 'Ошибка'), ('REFUNDED', 'Возврат'), ('CANCELED', 'Отменено')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции провайдера')),
                ('payment_url', models.URLField(blank=True, verbose_name='URL оплаты')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='bookings.booking', verbose_name='Бронь')),
                ('lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='lobby.lobby', verbose_name='Лобби')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_session', to='finance.transaction', verbose_name='Транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='memberships.usermembership', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Платёжная сессия',
                'verbose_name_plural': 'Платёжные сессии',
                'ordering': ['-created_at'],
            },
        ),
    ]
