# Generated by Django 4.2.27 on 2025-12-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_elo',
            field=models.IntegerField(default=1200, verbose_name='ELO Rating'),
        ),
    ]
