# Generated by Django 4.2.27 on 2025-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rating_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за час (для тренера)'),
        ),
    ]
