# Generated by Django 4.2.27 on 2025-12-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_qr_blocked',
            field=models.BooleanField(default=False, verbose_name='Блокировка QR (проверка личности)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID последнего устройства'),
        ),
    ]
