# Generated by Django 4.2.27 on 2026-02-16 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('RECEPTIONIST', 'Receptionist'), ('COACH_PADEL', 'Padel Coach'), ('COACH_FITNESS', 'Fitness Coach'), ('CLIENT', 'Client')], default='CLIENT', max_length=20, verbose_name='Role'),
        ),
    ]
