# Generated by Django 4.2.27 on 2026-03-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_created_at_user_updated_at_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('RECEPTIONIST', 'Receptionist'), ('SALES_MANAGER', 'Sales Manager'), ('COACH_PADEL', 'Padel Coach'), ('COACH_FITNESS', 'Fitness Coach'), ('CLIENT', 'Client')], default='CLIENT', max_length=20, verbose_name='Role'),
        ),
    ]
