# Generated by Django 4.2.27 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_coach_price_by_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за час (для тренера, по умолчанию)'),
        ),
    ]
