# Generated by Django 4.2.27 on 2026-03-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('source', models.CharField(choices=[('PHONE_CALL', 'Звонок'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Сайт'), ('WALK_IN', 'Пришёл сам'), ('REFERRAL', 'Рекомендация'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Источник')),
                ('stage', models.CharField(choices=[('NEW', 'Новые обращения'), ('IN_PROGRESS', 'В работе'), ('NEGOTIATION', 'Переговоры'), ('SOLD', 'Успешная продажа'), ('LOST', 'Закрыто / потеря')], default='NEW', max_length=20, verbose_name='Стадия')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('last_contact', models.DateTimeField(blank=True, null=True, verbose_name='Последний контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'RECEPTIONIST']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Назначен менеджеру')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('due_datetime', models.DateTimeField(verbose_name='Срок выполнения')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Задача по лиду',
                'verbose_name_plural': 'Задачи по лидам',
                'ordering': ['due_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leads.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Комментарий к лиду',
                'verbose_name_plural': 'Комментарии к лидам',
                'ordering': ['created_at'],
            },
        ),
    ]
