# Generated by Django 4.2.27 on 2025-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название/Номер корта')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Покрытие')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за час (базовая)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courts/', verbose_name='Фото корта')),
            ],
            options={
                'verbose_name': 'Корт',
                'verbose_name_plural': 'Корты',
                'ordering': ['name'],
            },
        ),
    ]
