# Generated by Django 4.2.27 on 2025-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('INDOOR', 'Indoor (Крытый)'), ('OUTDOOR', 'Outdoor (Открытый)'), ('PANORAMIC', 'Panoramic (Панорамный)')], default='INDOOR', max_length=20, verbose_name='Тип корта'),
        ),
        migrations.AlterField(
            model_name='court',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='court',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=8000.0, max_digits=10, verbose_name='Цена за час'),
        ),
    ]
