# Generated by Django 4.2.27 on 2025-12-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_court_type_alter_court_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courts/', verbose_name='Главное фото'),
        ),
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courts/gallery/', verbose_name='Фото')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='courts.court', verbose_name='Корт')),
            ],
        ),
    ]
