# Generated by Django 4.2.27 on 2026-03-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_alter_court_image_courtimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='play_format',
            field=models.CharField(choices=[('TWO_VS_TWO', '2x2 (Двое на двое)'), ('ONE_VS_ONE', '1x1 (Один на один)')], default='TWO_VS_TWO', help_text='2x2 — Panoramic корты (4 игрока), 1x1 — Single корт (2 игрока)', max_length=20, verbose_name='Формат игры'),
        ),
        migrations.AlterField(
            model_name='court',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Используется как резерв, если не заданы ценовые слоты', max_digits=10, verbose_name='Цена за час (базовая / резерв)'),
        ),
        migrations.CreateModel(
            name='CourtPriceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Например: 06:00', verbose_name='Начало слота')),
                ('end_time', models.TimeField(help_text='Например: 08:00. Для полуночи (конец суток) укажите 00:00', verbose_name='Конец слота')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час в этом слоте')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_slots', to='courts.court', verbose_name='Корт')),
            ],
            options={
                'verbose_name': 'Ценовой слот корта',
                'verbose_name_plural': 'Ценовые слоты кортов',
                'ordering': ['court', 'start_time'],
            },
        ),
    ]
