# Generated by Django 4.2.27 on 2026-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_add_play_format_and_price_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('INDOOR', 'Indoor (Крытый)'), ('OUTDOOR', 'Outdoor (Открытый)'), ('PANORAMIC', 'Panoramic (Панорамный)'), ('SQUASH', 'Squash'), ('PING_PONG', 'Ping-pong (Настольный теннис)')], default='INDOOR', max_length=20, verbose_name='Тип корта'),
        ),
    ]
