# Generated by Django 4.2.27 on 2025-12-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ настройки')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка клуба',
                'verbose_name_plural': 'Настройки клуба (Core)',
            },
        ),
    ]
