# Generated by Django 4.2.27 on 2025-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clubsetting_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата закрытия')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина (Например: Новый Год)')),
            ],
            options={
                'verbose_name': 'Выходной / Спец. день',
                'verbose_name_plural': 'Выходные и Праздники (Core)',
                'ordering': ['date'],
            },
        ),
    ]
