# Generated by Django 4.2.27 on 2025-12-19 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (KZT)')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Оплата бронирования'), ('REFUND', 'Возврат средств'), ('SALARY', 'Выплата зарплаты'), ('OTHER', 'Прочее')], default='PAYMENT', max_length=20, verbose_name='Тип операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bookings.booking', verbose_name='Связанная бронь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Финансы (Транзакции)',
                'ordering': ['-created_at'],
            },
        ),
    ]
