# Generated by Django 4.2.27 on 2025-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_coach',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='За тренера'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_court',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='За корт'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_services',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='За инвентарь'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ИТОГО'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (для людей)'),
        ),
    ]
