# Generated by Django 4.2.27 on 2025-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_amount_coach_transaction_amount_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
    ]
