# Generated by Django 4.2.27 on 2025-12-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershiptype_discount_on_court_and_more'),
        ('finance', '0003_transaction_amount_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('KASPI', 'Kaspi / QR'), ('CARD', 'Банковская карта'), ('CASH', 'Наличные'), ('BONUS', 'Бонусы'), ('UNKNOWN', 'Не указано')], default='UNKNOWN', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='memberships.usermembership', verbose_name='Купленный абонемент'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BOOKING', 'Оплата бронирования'), ('MEMBERSHIP', 'Покупка абонемента'), ('REFUND', 'Возврат средств'), ('SALARY', 'Выплата зарплаты'), ('OTHER', 'Прочее')], default='BOOKING', max_length=20, verbose_name='Тип операции'),
        ),
    ]
