# Generated by Django 4.2.27 on 2026-03-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('finance', '0004_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tournament_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tournaments.tournamentteam', verbose_name='Команда турнира'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BOOKING', 'Оплата бронирования'), ('MEMBERSHIP', 'Покупка абонемента'), ('REFUND', 'Возврат средств'), ('TOURNAMENT_FEE', 'Взнос за турнир'), ('SALARY', 'Выплата зарплаты'), ('OTHER', 'Прочее')], default='BOOKING', max_length=20, verbose_name='Тип операции'),
        ),
    ]
