# Generated by Django 4.2.27 on 2026-03-13 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн регистрации')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('REGISTRATION', 'Открыта регистрация'), ('IN_PROGRESS', 'Идёт турнир'), ('COMPLETED', 'Завершён'), ('CANCELED', 'Отменён')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('format', models.CharField(choices=[('SINGLES', 'Одиночный'), ('DOUBLES', 'Парный падел')], default='DOUBLES', max_length=20, verbose_name='Формат')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Платный')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Взнос (₸)')),
                ('max_teams', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым — без ограничений', null=True, verbose_name='Макс. команд')),
                ('prize_info', models.TextField(blank=True, verbose_name='Призовой фонд / условия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, help_text='Если пусто — генерируется из имён игроков', max_length=100, verbose_name='Название команды')),
                ('status', models.CharField(choices=[('PENDING', 'Заявка'), ('CONFIRMED', 'Подтверждён'), ('PAID', 'Оплачен'), ('WITHDRAWN', 'Снят'), ('REFUNDED', 'Возврат')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Наличные'), ('KASPI', 'Kaspi'), ('CARD', 'Карта'), ('OTHER', 'Другое')], max_length=20, verbose_name='Способ оплаты')),
                ('seed', models.PositiveIntegerField(blank=True, help_text='1 = топ-сид. Влияет на жеребьёвку сетки', null=True, verbose_name='Сид (посев)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tournament_payments', to=settings.AUTH_USER_MODEL, verbose_name='Оплату принял')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_teams_p1', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 1')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_teams_p2', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 2 (пара)')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['seed', 'registered_at'],
                'unique_together': {('tournament', 'player1')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Раунд')),
                ('match_number', models.PositiveIntegerField(verbose_name='Номер матча в раунде')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время матча')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Запланирован'), ('IN_PROGRESS', 'Идёт'), ('COMPLETED', 'Завершён'), ('POSTPONED', 'Перенесён'), ('WALKOVER', 'Технический выигрыш')], default='SCHEDULED', max_length=20, verbose_name='Статус')),
                ('score_team1', models.CharField(blank=True, max_length=50, verbose_name='Счёт команды 1')),
                ('score_team2', models.CharField(blank=True, max_length=50, verbose_name='Счёт команды 2')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.court', verbose_name='Корт')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_matches', to='tournaments.tournamentmatch', verbose_name='Следующий матч')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team1', to='tournaments.tournamentteam', verbose_name='Команда 1')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team2', to='tournaments.tournamentteam', verbose_name='Команда 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Турнир')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.tournamentteam', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['round_number', 'match_number'],
                'unique_together': {('tournament', 'round_number', 'match_number')},
            },
        ),
    ]
