# Generated by Django 4.2.27 on 2025-12-20 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет показа')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Промокод (если есть)')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Процент (%)'), ('FIXED', 'Фиксированная сумма (₸)')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Величина скидки')),
                ('start_date', models.DateTimeField(verbose_name='Начало')),
                ('end_date', models.DateTimeField(verbose_name='Конец')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Маркетинг (Акции)',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
