# Generated by Django 4.2.27 on 2025-12-19 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Кол-во часов')),
                ('days_valid', models.PositiveIntegerField(default=30, verbose_name='Срок действия (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='В продаже')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('hours_remaining', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Остаток часов')),
                ('is_active', models.BooleanField(default=True)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.membershiptype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
