# Generated by Django 4.2.27 on 2025-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='freeze_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала заморозки'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Заморожен'),
        ),
    ]
