# Generated by Django 4.2.27 on 2025-12-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_usermembership_freeze_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='discount_on_court',
            field=models.IntegerField(default=0, verbose_name='Скидка на Падел (%)'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='service_type',
            field=models.CharField(choices=[('PADEL', 'Падел (Часы)'), ('GYM_UNLIMITED', 'Фитнес (Безлимит)'), ('GYM_PACK', 'Фитнес (Пакет посещений)')], default='PADEL', max_length=20, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Посещения (для Gym Pack)'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='visits_remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток посещений'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Часы (для Падела)'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='hours_remaining',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Остаток часов'),
        ),
    ]
