# Generated by Django 4.2.27 on 2026-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershiptype_discount_on_court_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'ordering': ['service_type', 'name'], 'verbose_name': 'Тип абонемента', 'verbose_name_plural': 'Типы абонементов'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'ordering': ['-start_date'], 'verbose_name': 'Абонемент пользователя', 'verbose_name_plural': 'Абонементы пользователей'},
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='court_type_restriction',
            field=models.CharField(blank=True, choices=[('', 'Любой корт'), ('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('PANORAMIC', 'Panoramic')], default='', help_text='Пусто = любой корт', max_length=20, verbose_name='Ограничение по типу корта'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание / Комментарий'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='includes_coach',
            field=models.BooleanField(default=False, help_text='Если да — стоимость тренера покрывается пакетом', verbose_name='Включает тренера'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='max_participants',
            field=models.PositiveIntegerField(default=4, verbose_name='Макс. участников'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='min_participants',
            field=models.PositiveIntegerField(default=1, verbose_name='Мин. участников'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='prime_time_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Если бронь вне приоритетного окна — доплата за каждый час', max_digits=10, verbose_name='Доплата за прайм-тайм (₸/час)'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='priority_time_end',
            field=models.TimeField(blank=True, help_text='Время без доплаты, напр. 15:00', null=True, verbose_name='Приоритетное время — конец'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='priority_time_start',
            field=models.TimeField(blank=True, help_text='Время без доплаты, напр. 06:00', null=True, verbose_name='Приоритетное время — начало'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='discount_on_court',
            field=models.IntegerField(default=0, help_text='Скидка которую даёт этот абонемент на обычную аренду', verbose_name='Скидка на аренду корта (%)'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₸)'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='service_type',
            field=models.CharField(choices=[('PADEL_HOURS', 'Падел — Пакет часов'), ('TRAINING_HOURS', 'Тренировки с тренером — Пакет часов'), ('GYM', 'Фитнес — Безлимит'), ('VIP', 'VIP — Комбо пакет')], default='PADEL_HOURS', max_length=20, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Для PADEL_HOURS и TRAINING_HOURS', max_digits=6, verbose_name='Часы в пакете'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Посещения (для фитнес-пакетов)'),
        ),
    ]
