# Generated by Django 4.2.27 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_migrate_service_type_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Если пусто или 0 — без лимита по количеству.', null=True, verbose_name='Макс. количество проданных экземпляров'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='court_type_restriction',
            field=models.CharField(blank=True, choices=[('', 'Любой корт'), ('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('PANORAMIC', 'Panoramic'), ('SQUASH', 'Squash'), ('PING_PONG', 'Ping-pong')], default='', help_text='Пусто = любой корт', max_length=20, verbose_name='Ограничение по типу корта'),
        ),
    ]
