# Generated by Django 4.2.27 on 2025-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (Ракетка, Вода)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно для выбора')),
            ],
            options={
                'verbose_name': 'Услуга / Инвентарь',
                'verbose_name_plural': 'Инвентарь',
            },
        ),
    ]
