# Generated by Django 4.2.27 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('INVENTORY', 'Инвентарь / Аренда'), ('SERVICE', 'Услуга'), ('FOOD', 'Еда'), ('DRINK', 'Напиток'), ('EVENT', 'Турнир / Мероприятие')], default='INVENTORY', help_text='Инвентарь, услуга, еда, напиток, турнир и т.п.', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Опционально. Пояснение для клиента.', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.CharField(choices=[('PADEL', 'Падел / Корты'), ('GYM', 'Фитнес / Зал'), ('RECOVERY', 'Recovery / Массаж'), ('SPORT_BAR', 'Спорт-бар'), ('OTHER', 'Другое')], default='OTHER', help_text='Например: Падел, Фитнес/зал, Recovery, Спорт-бар.', max_length=20, verbose_name='Группа (где используется)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Опционально. Отображается в карточке услуги / позиции.', null=True, upload_to='inventory/', verbose_name='Фото'),
        ),
    ]
