"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # Добавляем это
from datetime import timedelta

# Загружаем переменные из .env
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')

CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app']
# Application definition
# Исправление ссылок для ngrok / прокси
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist', # <--- Обязательно добавь это

    # Сторонние библиотеки
    'rest_framework',  # Для API мобилки
    'djoser',
    'drf_yasg',
    'corsheaders',  # <--- Добавь это
    # Наши приложения (Apps)
    'users.apps.UsersConfig',
    'courts.apps.CourtsConfig',
    'bookings.apps.BookingsConfig',
    'finance.apps.FinanceConfig',
    'gamification.apps.GamificationConfig',
    'inventory.apps.InventoryConfig',
    'core.apps.CoreConfig',
    'memberships.apps.MembershipsConfig',
    'marketing.apps.MarketingConfig',
    'gym.apps.GymConfig',
    'analytics.apps.AnalyticsConfig',
    'friends.apps.FriendsConfig',
    'news.apps.NewsConfig',
    'lobby.apps.LobbyConfig',
    'notifications.apps.NotificationsConfig',
    'payments.apps.PaymentsConfig',
]

# Настройки DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', # Используем JWT
        'rest_framework.authentication.SessionAuthentication', # Оставляем для админки
        
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Эти значения перезаписываются в views.py через кастомные throttle-классы,
        # но на всякий случай:
        'anon': '100/hour',
    },
}

# Настройки Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),   # Пропуск (1 день)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90), # 🔥 Паспорт (3 месяца - чтобы не вылетало)
    'ROTATE_REFRESH_TOKENS': True, # Обновлять паспорт при каждом использовании
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Настройки Djoser (регистрация и управление юзерами)
DJOSER = {
    'LOGIN_FIELD': 'email',  # Или 'username', как у тебя настроено
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'SEND_CONFIRMATION_EMAIL': False,
    'SET_USERNAME_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False,
    
    # ВОТ ЭТО САМОЕ ВАЖНОЕ: ССЫЛКА НА ТВОЙ ФАЙЛ
    'SERIALIZERS': {
        'user_create': 'users.serializers.UserCreateSerializer',
        'user': 'users.serializers.UserSerializer',          # <-- Это для списка
        'current_user': 'users.serializers.UserSerializer',  # <-- Это для /users/me/
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # <--- Добавь это
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# settings.py

SWAGGER_SETTINGS = {
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
    'USE_SESSION_AUTH': False,
    'DEFAULT_MODEL_SERIALIZER_CLASS': 'rest_framework.serializers.ModelSerializer',
    
    # 👇 ДОБАВЛЯЕМ ЭТОТ БЛОК, ЧТОБЫ ПОЯВИЛОСЬ ПОЛЕ ДЛЯ ТОКЕНА
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'  # Можно сразу поставить русский язык админки

TIME_ZONE = 'Asia/Almaty'  # <--- СТАВИМ КАЗАХСТАН

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'  # Папка, куда сервер соберет все файлы

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'    # Папка для аватарок

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Указываем Django использовать нашу модель пользователя
AUTH_USER_MODEL = 'users.User'


# CORS SETTINGS
CORS_ALLOW_ALL_ORIGINS = True  # Разрешить всем стучаться к нам
CORS_ALLOW_CREDENTIALS = True

# ============================================================
# PAYMENT SETTINGS
# ============================================================
# Текущий провайдер: 'stub' (разработка) | 'kaspi' (продакшн)
# Для переключения на Kaspi:
#   1. Задай PAYMENT_PROVIDER=kaspi в .env
#   2. Задай KASPI_MERCHANT_ID и KASPI_SECRET_KEY в .env
#   3. Реализуй KaspiPaymentProvider в payments/providers/kaspi.py
PAYMENT_PROVIDER = os.getenv('PAYMENT_PROVIDER', 'stub')

# Kaspi QR / Kaspi Pay (заполнить при подключении)
KASPI_MERCHANT_ID = os.getenv('KASPI_MERCHANT_ID', '')
KASPI_SECRET_KEY  = os.getenv('KASPI_SECRET_KEY', '')

# ============================================================
# SMS SETTINGS
# ============================================================
# Мастер-код для разработки — принимается вместо реального SMS-кода.
# В продакшне обязательно убрать (оставить пустым или удалить из .env).
# Использование: введи этот код вместо реального в любой форме верификации.
SMS_MASTER_CODE = os.getenv('SMS_MASTER_CODE', '000000')