# Generated by Django 4.2.27 on 2026-02-26 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название лобби')),
                ('game_format', models.CharField(choices=[('SINGLE', 'Одиночная (1 на 1)'), ('DOUBLE', 'Парная (2 на 2)')], default='DOUBLE', max_length=10, verbose_name='Формат')),
                ('level', models.CharField(choices=[('BEGINNER', 'Новичок'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый'), ('PRO', 'Профи')], default='INTERMEDIATE', max_length=15, verbose_name='Уровень')),
                ('status', models.CharField(choices=[('OPEN', 'Ищем игроков'), ('WAITING', 'Ожидание (частично заполнено)'), ('READY', 'Готово к игре'), ('CLOSED', 'Закрыто')], default='OPEN', max_length=10, verbose_name='Статус')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Желаемое время игры')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lobbies', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Лобби',
                'verbose_name_plural': 'Лобби (поиск партнёров)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LobbyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lobby.lobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник лобби',
                'unique_together': {('lobby', 'user')},
            },
        ),
    ]
