# Generated by Django 4.2.27 on 2026-02-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_participants'),
        ('courts', '0003_alter_court_image_courtimage'),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby', to='bookings.booking', verbose_name='Созданная бронь'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.court', verbose_name='Желаемый корт'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='duration_minutes',
            field=models.IntegerField(default=90, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='lobbyparticipant',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='lobbyparticipant',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lobbyparticipant',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lobbyparticipant',
            name='team',
            field=models.CharField(blank=True, choices=[('A', 'Команда A'), ('B', 'Команда B')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='game_format',
            field=models.CharField(choices=[('SINGLE', 'Одиночная (1×1, 2 игрока)'), ('DOUBLE', 'Парная (2×2, 4 игрока)')], default='DOUBLE', max_length=10, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ищем игроков'), ('WAITING', 'Ожидание (частично заполнено)'), ('READY', 'Готово — ждём оплату'), ('BOOKED', 'Бронь создана'), ('CLOSED', 'Закрыто')], default='OPEN', max_length=10, verbose_name='Статус'),
        ),
    ]
