# Generated by Django 4.2.27 on 2026-02-26 09:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('lobby', '0002_lobby_booking_lobby_court_lobby_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyparticipant',
            name='court_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='lobbyparticipant',
            name='membership_used',
            field=models.BooleanField(default=False, verbose_name='Абонемент использован'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ищем игроков'), ('WAITING', 'Ожидание (частично заполнено)'), ('READY', 'Готово — ждём бронь'), ('BOOKED', 'Бронь создана — ждём оплату'), ('PAID', 'Все оплатили — бронь подтверждена'), ('CLOSED', 'Закрыто')], default='OPEN', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='LobbyParticipantExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_moment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент добавления')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='lobby.lobbyparticipant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.service', verbose_name='Услуга/Инвентарь')),
            ],
            options={
                'verbose_name': 'Доп. услуга участника лобби',
            },
        ),
    ]
