# Generated by Django 4.2.27 on 2026-02-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0003_alter_court_image_courtimage'),
        ('lobby', '0003_lobbyparticipant_court_share_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='level',
        ),
        migrations.AddField(
            model_name='lobby',
            name='elo_max',
            field=models.PositiveIntegerField(default=9999, verbose_name='ELO максимум'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='elo_min',
            field=models.PositiveIntegerField(default=0, verbose_name='ELO минимум'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.court', verbose_name='Корт (после согласования)'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время игры (после согласования)'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ищем игроков'), ('WAITING', 'Частично заполнено'), ('NEGOTIATING', 'Согласование времени/корта'), ('READY', 'Время согласовано — ждём бронь'), ('BOOKED', 'Бронь создана — ждём оплату'), ('PAID', 'Все оплатили — бронь подтверждена'), ('CLOSED', 'Закрыто')], default='OPEN', max_length=12, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='LobbyTimeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(verbose_name='Предлагаемое время')),
                ('duration_minutes', models.IntegerField(default=90, verbose_name='Длительность (мин)')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court', verbose_name='Корт')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='lobby.lobby')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_proposals', to=settings.AUTH_USER_MODEL)),
                ('votes', models.ManyToManyField(blank=True, related_name='voted_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Голоса «за»')),
            ],
            options={
                'verbose_name': 'Предложение времени',
                'ordering': ['-created_at'],
            },
        ),
    ]
