# Generated by Django 4.2.27 on 2025-12-20 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_trainings_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_trainings_coach', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Персональная тренировка (Gym)',
                'verbose_name_plural': 'Тренировки (Gym)',
            },
        ),
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('checkin_type', models.CharField(choices=[('SUBSCRIPTION', 'По абонементу'), ('ONE_TIME', 'Разовый (Платный)')], max_length=20, verbose_name='Тип входа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_visits', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Посещение зала',
                'verbose_name_plural': 'Посещения зала',
            },
        ),
    ]
