# Generated by Django 4.2.27 on 2025-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(verbose_name='Конец аренды'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='Начало аренды'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Подтверждено'), ('PENDING', 'Ожидает оплаты'), ('CANCELED', 'Отменено'), ('COMPLETED', 'Завершено')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
