# Generated by Django 4.2.27 on 2025-12-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_rename_client_booking_user_remove_booking_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
