# Generated by Django 4.2.27 on 2025-12-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('bookings', '0004_booking_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_moment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент покупки')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bookings.booking', verbose_name='Бронь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.service', verbose_name='Услуга')),
            ],
        ),
    ]
