# Generated by Django 4.2.27 on 2025-12-25 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_bookingservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Участники (Друзья)'),
        ),
    ]
