# Generated by Django 4.2.27 on 2026-03-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershiptype_discount_on_court_and_more'),
        ('bookings', '0006_booking_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='membership_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_paid_by_hours', to='memberships.usermembership', verbose_name='Оплачено по абонементу'),
        ),
    ]
