# Generated by Django 4.2.27 on 2025-12-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0002_court_court_type_alter_court_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50, verbose_name='Счет матча')),
                ('winner_team', models.CharField(choices=[('A', 'Команда А'), ('B', 'Команда Б'), ('DRAW', 'Ничья')], max_length=10, verbose_name='Победитель')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата игры')),
                ('is_rated', models.BooleanField(default=False, verbose_name='Рейтинг начислен')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.court', verbose_name='Корт')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judged_matches', to=settings.AUTH_USER_MODEL, verbose_name='Судья/Тренер')),
                ('team_a', models.ManyToManyField(related_name='matches_as_team_a', to=settings.AUTH_USER_MODEL, verbose_name='Команда А')),
                ('team_b', models.ManyToManyField(related_name='matches_as_team_b', to=settings.AUTH_USER_MODEL, verbose_name='Команда Б')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
