# Generated by Django 4.2.27 on 2026-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elo_changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Изменения ELO'),
        ),
    ]
