# Generated by Django 4.2.27 on 2026-02-26 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING', 'Бронирование'), ('MEMBERSHIP', 'Абонемент'), ('FRIEND', 'Друзья'), ('MATCH', 'Матч / ELO'), ('LOBBY', 'Лобби'), ('PROMO', 'Акция'), ('NEWS', 'Новость'), ('PAYMENT', 'Оплата'), ('SYSTEM', 'Система')], default='SYSTEM', max_length=15, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные (доп.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
