# Generated by Django 4.2.27 on 2026-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING', 'Бронирование'), ('MEMBERSHIP', 'Абонемент'), ('FRIEND', 'Друзья'), ('MATCH', 'Матч / ELO'), ('LOBBY', 'Лобби'), ('PROMO', 'Акция'), ('NEWS', 'Новость'), ('PAYMENT', 'Оплата'), ('MESSAGE', 'Сообщение'), ('SYSTEM', 'Система')], default='SYSTEM', max_length=15, verbose_name='Тип'),
        ),
    ]
